#!/bin/bash

while getopts ":e:d:" opt; do
    case $opt in
      e)
        echo "Encrypting $OPTARG ..." >&2
	node -pe "Buffer.from('$OPTARG').toString('base64')" >&2
        ;;
      d)
	echo "Decrypting $OPTARG" >&2
	node -pe "Buffer.from('$OPTARG', 'base64').toString()" >&2
	;;
      \?)
        echo "Invalid Option: -$OPTARG" >&2
        exit 1
        ;;
      :)
        echo "Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
    esac
done

